#!/usr/bin/env bash
DOTFILES=$(pwd)

# Set OSX Defaults
source osx.sh

# Install Homebrew Packages
source brew.sh

# Install NPM Packages
source npm.sh

# Install ruby gems
source gem.sh

# Install Atom Packages
apm install --packages-file=atom/packages.txt

# Install Vagrant Plugins
vagrant plugin install vagrant-hostsupdater
vagrant plugin install vagrant-vbguest

# Configure git config & ignore
git config --global include.path $DOTFILES/git/.gitconfig
git config --global core.excludesfile $DOTFILES/git/.gitignore

# Run secrets
./secrets

# Setup Symlinks
ln -svf $DOTFILES/.vimrc ~

mkdir -v ~/.atom
ln -vsf $DOTFILES/atom/keymap.cson $DOTFILES/atom/config.cson  ~/.atom

mkdir -pv ~/.config/fish
ln -svf $DOTFILES/fish/config.fish $DOTFILES/fish/functions ~/.config/fish
