#!/usr/bin/env bash
DOTFILES=$(pwd)

# Install Homebrew Packages
source brew.sh

# Set OSX Defaults
source osx.sh

# Install Atom Packages
apm install --packages-file=atom/packages.txt

# Configure git config & ignore
git config --global include.path $DOTFILES/git/.gitconfig
git config --global core.excludesfile $DOTFILES/git/.gitignore

# Run secrets
./secrets

# Setup Symlinks
ln -svf $DOTFILES/vimrc ~
ln -svf $DOTFILES/atom/config.cson ~/.atom
ln -svf $DOTFILES/atom/keymap.cson ~/.atom
ln -svf $DOTFILES/fish/config.fish ~/.config/fish
ln -svf $DOTFILES/fish/functions/ ~/.config/fish/functions/
