#!/usr/bin/env bash
DOTFILES=$(pwd)

# Set OSX Defaults
source osx.sh

# Install Homebrew Packages
source brew.sh

# Install Ruby & Gems
source gem.sh

# Install Atom Packages
apm install --packages-file=atom/packages.txt

# Install Vagrant Plugins
vagrant plugin install vagrant-hostsupdater

# Configure git config & ignore
git config --global include.path $DOTFILES/git/.gitconfig
git config --global core.excludesfile $DOTFILES/git/.gitignore

# Run secrets
./secrets

# Setup Symlinks
ln -svf $DOTFILES/.vimrc ~
ln -svf $DOTFILES/.gemrc ~

mkdir -v ~/.atom
ln -vsf $DOTFILES/atom/keymap.cson $DOTFILES/atom/config.cson $DOTFILES/atom/styles.less  ~/.atom

mkdir -pv ~/.config/fish
ln -svf $DOTFILES/fish/config.fish $DOTFILES/fish/functions ~/.config/fish
