#!/usr/bin/env fish

# This command serves as a useful way of updating your machine
# periodically. It performs the most common package manager updates
# however it is not designed to install new packages. For that it
# is still best to run the install command

# Upgrade all homebrew packages (doesn't upgrade casks)
brew upgrade

# Upgrade brew casks (even if they auto update)
brew upgrade --cask --greedy

brew cleanup

# Finally update fish completions
fish_update_completions
